name: 'program-tests'
on: push
jobs:
    program-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.12.2'
          - name: Run tests
            run: |
              python3 run_integral_tests.py
